// Inverse Dynamics: a hands-on 2-D Newton-Euler solver students can drive.
//
// Everything on the page is computed live from the posture and forces the reader sets.
// Nothing is precomputed, so any line of the arithmetic can be checked by hand.
//
// Frame: x forward (+), y up (+), ground at y = 0. Moments are z-components,
// counter-clockwise positive. SI units throughout (m, kg, N, N·m, rad/s²).
//
// Sources for the segment parameter tables and the history markers are cited in
// TABLES and TIMELINE below, and repeated in the page's own source note.

(function () {
  "use strict";

  const PL = () => window.i18n && window.i18n.lang === "pl";
  const T = (en, pl) => (PL() ? pl : en);
  const G = 9.81;

  // ---------------------------------------------------------------- quotes
  // Short, attributed, shown on hover. Page and wording checked against the PDF.
  const Q = {
    notmeasurable: {
      en: "important variables, including the forces generated by muscles, are not generally measurable in experiments",
      pl: "ważne wielkości, w tym siły wytwarzane przez mięśnie, na ogół nie są mierzalne w eksperymencie",
      c: "Delp et al. 2007, p. 1940",
    },
    emglimit: {
      en: "electromyographic (EMG) recordings can indicate when a muscle is active, but examination of EMG recordings does not allow one to determine which motions of the body arise from a muscle's activity",
      pl: "zapisy elektromiograficzne (EMG) mogą wskazać, kiedy mięsień jest aktywny, ale ich analiza nie pozwala ustalić, które ruchy ciała wynikają z działania tego mięśnia",
      c: "Delp et al. 2007, p. 1940",
    },
    notspan: {
      en: "a muscle can accelerate joints that it does not span and body segments to which it does not attach",
      pl: "mięsień może przyspieszać stawy, których nie przekracza, i segmenty ciała, do których się nie przyczepia",
      c: "Delp et al. 2007, p. 1940",
    },
    complement: {
      en: "Muscle-driven dynamic simulations complement experimental approaches by providing estimates of important variables, such as muscle and joint forces, which are difficult to measure experimentally.",
      pl: "Symulacje dynamiczne napędzane mięśniami uzupełniają podejście eksperymentalne, dostarczając oszacowań ważnych wielkości, takich jak siły mięśniowe i stawowe, które trudno zmierzyć doświadczalnie.",
      c: "Delp et al. 2007, p. 1940",
    },
    inconsistent: {
      en: "measured ground reaction forces and moments are often dynamically inconsistent with the model kinematics",
      pl: "zmierzone siły i momenty reakcji podłoża są często dynamicznie niezgodne z kinematyką modelu",
      c: "Delp et al. 2007, p. 1943",
    },
    residual: {
      en: "In the absence of experimental and modeling error, the residual force should be zero (i.e., F residual = 0). In practice, this is never the case.",
      pl: "Przy braku błędu eksperymentalnego i modelowego siła resztkowa powinna wynosić zero (tzn. F resztkowa = 0). W praktyce nigdy tak nie jest.",
      c: "Delp et al. 2007, p. 1943",
    },
    reproduce: {
      en: "The inability to reproduce results is a major limitation to advancing the science of biomedical simulation.",
      pl: "Niemożność odtworzenia wyników jest poważnym ograniczeniem dla rozwoju nauki o symulacji biomedycznej.",
      c: "Delp et al. 2007, p. 1941",
    },
    testlimits: {
      en: "Given that simulations include assumptions and approximations, it is critically important that each simulation be tested to establish its limitations.",
      pl: "Ponieważ symulacje zawierają założenia i przybliżenia, sprawą krytycznie ważną jest przetestowanie każdej symulacji, aby ustalić jej ograniczenia.",
      c: "Delp et al. 2007, p. 1946",
    },
    fidelity: {
      en: "The accuracy of a simulation depends on the fidelity of the underlying mathematical model of the neuromusculoskeletal system.",
      pl: "Dokładność symulacji zależy od wierności leżącego u jej podstaw matematycznego modelu układu nerwowo-mięśniowo-szkieletowego.",
      c: "Delp et al. 2007, p. 1946",
    },
    freely: {
      en: "OpenSim is being developed and maintained on Simtk.org; all of the software is freely available.",
      pl: "OpenSim jest rozwijany i utrzymywany na Simtk.org; całe oprogramowanie jest dostępne bezpłatnie.",
      c: "Delp et al. 2007, p. 1941, Fig. 1",
    },
  };

  let tip = null;
  function ensureTip() {
    if (tip) return tip;
    tip = document.createElement("div");
    tip.className = "id-tip";
    document.body.appendChild(tip);
    return tip;
  }
  function showTip(key, x, y) {
    const q = Q[key];
    if (!q) return;
    const t = ensureTip(), pl = PL();
    t.innerHTML =
      '<span class="id-tip-q">' + (pl ? "„" + q.pl + "”" : "“" + q.en + "”") + "</span>" +
      (pl ? '<span class="id-tip-orig">oryginał: “' + q.en + '”</span>' : "") +
      '<span class="id-tip-c">' + q.c + "</span>";
    t.classList.add("in");
    moveTip(x, y);
  }
  function moveTip(x, y) {
    if (!tip) return;
    const pad = 16, r = tip.getBoundingClientRect();
    let nx = x + pad, ny = y + pad;
    if (nx + r.width > window.innerWidth - 10) nx = x - r.width - pad;
    if (ny + r.height > window.innerHeight - 10) ny = y - r.height - pad;
    tip.style.left = Math.max(8, nx) + "px";
    tip.style.top = Math.max(8, ny) + "px";
  }
  function hideTip() { if (tip) tip.classList.remove("in"); }

  function wireQuotes(root) {
    root.querySelectorAll(".q").forEach(el => {
      if (el.dataset.wired) return;
      el.dataset.wired = "1";
      el.tabIndex = 0;
      el.addEventListener("mouseenter", e => showTip(el.dataset.q, e.clientX, e.clientY));
      el.addEventListener("mousemove", e => moveTip(e.clientX, e.clientY));
      el.addEventListener("mouseleave", hideTip);
      el.addEventListener("focus", () => {
        const r = el.getBoundingClientRect();
        showTip(el.dataset.q, r.left, r.bottom);
      });
      el.addEventListener("blur", hideTip);
      el.addEventListener("click", e => {          // touch
        e.preventDefault();
        showTip(el.dataset.q, e.clientX, e.clientY);
      });
    });
  }
  document.addEventListener("keydown", e => { if (e.key === "Escape") hideTip(); });
  window.addEventListener("scroll", hideTip, { passive: true });

  // ------------------------------------------------- body segment parameters
  // mass  = fraction of total body mass
  // com   = centre of mass position, fraction of segment length from the PROXIMAL end
  // rg    = radius of gyration about the CoM, fraction of segment length (sagittal)
  // len   = segment length as a fraction of standing height
  //
  // "winter"  Dempster's cadaver data as tabulated by Winter, Biomechanics and Motor
  //           Control of Human Movement, 4th ed., Table 4.1. Sex-independent.
  // "deleva"  Zatsiorsky & Seluyanov's gamma-scanner data on living subjects, adjusted
  //           by de Leva (1996) to joint-centre endpoints. Separate male/female values.
  const TABLES = {
    winter: {
      name: { en: "Dempster / Winter", pl: "Dempster / Winter" },
      note: {
        en: "8 embalmed cadavers, elderly men. The classic teaching table; one set of numbers for everybody.",
        pl: "8 zabalsamowanych zwłok, starsi mężczyźni. Klasyczna tabela dydaktyczna; jeden zestaw liczb dla wszystkich.",
      },
      cite: "Dempster 1955, as tabulated in Winter (2009) Table 4.1",
      sexed: false,
      seg: {
        foot:  { mass: 0.0145, com: 0.500, rg: 0.475 },
        shank: { mass: 0.0465, com: 0.433, rg: 0.302 },
        thigh: { mass: 0.1000, com: 0.433, rg: 0.323 },
      },
    },
    deleva: {
      name: { en: "Zatsiorsky–Seluyanov / de Leva", pl: "Zatsiorski–Sielujanow / de Leva" },
      note: {
        en: "100 living young men scanned with gamma rays in Moscow; 15 women added in 1990. Adjusted by de Leva to joint centres.",
        pl: "100 żywych młodych mężczyzn prześwietlonych promieniowaniem gamma w Moskwie; w 1990 dodano 15 kobiet. Przeliczone przez de Levę na środki stawów.",
      },
      cite: "Zatsiorsky & Seluyanov 1983, adjusted by de Leva (1996) Table 4",
      sexed: true,
      seg: {
        m: {
          foot:  { mass: 0.0137, com: 0.4415, rg: 0.257 },
          shank: { mass: 0.0433, com: 0.4395, rg: 0.251 },
          thigh: { mass: 0.1416, com: 0.4095, rg: 0.329 },
        },
        f: {
          foot:  { mass: 0.0129, com: 0.4014, rg: 0.299 },
          shank: { mass: 0.0481, com: 0.4352, rg: 0.267 },
          thigh: { mass: 0.1478, com: 0.3612, rg: 0.369 },
        },
      },
    },
  };

  // Winter's segment lengths as a fraction of standing height (Table 4.1).
  const LEN_FRAC = { foot: 0.152, shank: 0.246, thigh: 0.245, ankleHeight: 0.039 };

  function segParams() {
    const t = TABLES[STATE.table];
    return t.sexed ? t.seg[STATE.sex] : t.seg;
  }

  // ------------------------------------------------------------- shared state
  // Default posture: mid-stance, foot flat, for a 75 kg / 1.75 m adult.
  // Joint coordinates are in metres with the floor at y = 0.
  const STATE = {
    mass: 75,
    height: 1.75,
    table: "deleva",
    sex: "m",
    useInertia: false,
    hip:   { x: 0.020, y: 0.934 },
    knee:  { x: 0.010, y: 0.505 },
    ankle: { x: 0.000, y: 0.075 },
    heel:  { x: -0.060, y: 0.025 },
    toe:   { x: 0.206, y: 0.025 },
    cop:   { x: 0.045, y: 0 },
    grf:   { x: -30, y: 740 },
    // Only used when useInertia is on. Illustrative late-stance values.
    acc:   { foot: { x: 2.0, y: 1.5 }, shank: { x: 1.2, y: 0.8 }, thigh: { x: 0.8, y: 0.4 } },
    alpha: { foot: 12, shank: 4, thigh: -2 },
  };

  const subs = [];
  const onChange = fn => subs.push(fn);
  const emit = () => subs.forEach(f => f());

  // ------------------------------------------------------------- the mechanics
  const sub = (a, b) => ({ x: a.x - b.x, y: a.y - b.y });
  const len = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
  const lerp = (a, b, t) => ({ x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t });
  // 2-D cross product, z component: the moment of F applied at r about the origin.
  const cross = (r, F) => r.x * F.y - r.y * F.x;

  // Build the three segments, proximal joint last-solved-first order: foot, shank, thigh.
  function segments() {
    const P = segParams(), M = STATE.mass;
    const Lfoot = len(STATE.heel, STATE.toe);
    const Lshank = len(STATE.knee, STATE.ankle);
    const Lthigh = len(STATE.hip, STATE.knee);
    const mk = (key, L, a, b, joint, mass, comFrac, rg) => {
      const m = mass * M;
      return {
        key, L, m,
        I: m * Math.pow(rg * L, 2),
        com: lerp(a, b, comFrac),
        prox: joint,
        a: STATE.acc[key],
        alpha: STATE.alpha[key],
      };
    };
    return [
      // foot: inertial axis heel -> toe, but the joint is the ankle
      mk("foot", Lfoot, STATE.heel, STATE.toe, STATE.ankle, P.foot.mass, P.foot.com, P.foot.rg),
      mk("shank", Lshank, STATE.knee, STATE.ankle, STATE.knee, P.shank.mass, P.shank.com, P.shank.rg),
      mk("thigh", Lthigh, STATE.hip, STATE.knee, STATE.hip, P.thigh.mass, P.thigh.com, P.thigh.rg),
    ];
  }

  // The recursion. Start at the ground and climb.
  //   Newton:  F_prox = m·a − F_dist − m·g        (g = (0, −G), so −m·g = (0, +mG))
  //   Euler:   M_prox = I·α − M_dist − (r_prox × F_prox) − (r_dist × F_dist)
  // The ground applies NO moment at the centre of pressure. That is the definition of
  // the centre of pressure, and it is the only reason the chain has a starting point.
  function solve() {
    const segs = segments();
    const distalPointOf = ["cop", "ankle", "knee"];
    let Fdist = { x: STATE.grf.x, y: STATE.grf.y };
    let Mdist = 0;
    let dPoint = STATE.cop;
    const out = [];

    segs.forEach((s, i) => {
      const a = STATE.useInertia ? s.a : { x: 0, y: 0 };
      const al = STATE.useInertia ? s.alpha : 0;

      const Fp = {
        x: s.m * a.x - Fdist.x,
        y: s.m * a.y - Fdist.y + s.m * G,
      };
      const rp = sub(s.prox, s.com);
      const rd = sub(dPoint, s.com);
      const termP = cross(rp, Fp);
      const termD = cross(rd, Fdist);
      const inertial = s.I * al;
      const Mp = inertial - Mdist - termP - termD;

      out.push({
        seg: s, Fp, Mp, rp, rd, termP, termD, inertial,
        Fdist: { x: Fdist.x, y: Fdist.y }, Mdist, dPoint,
        weight: s.m * G,
        distalName: distalPointOf[i],
      });

      // Newton's third law hands the answer to the next segment up.
      Fdist = { x: -Fp.x, y: -Fp.y };
      Mdist = -Mp;
      dPoint = s.prox;
    });
    return out;
  }

  const JOINT_LABEL = {
    foot: { en: "Ankle", pl: "Staw skokowy" },
    shank: { en: "Knee", pl: "Kolano" },
    thigh: { en: "Hip", pl: "Biodro" },
  };
  const SEG_LABEL = {
    foot: { en: "Foot", pl: "Stopa" },
    shank: { en: "Shank", pl: "Podudzie" },
    thigh: { en: "Thigh", pl: "Udo" },
  };
  // Peak sagittal moments in level walking, for a plausibility check only.
  // Ranges are the usual textbook magnitudes (Winter 2009, ch. 7), not a norm.
  const PLAUSIBLE = { foot: [0, 1.8], shank: [0, 0.8], thigh: [0, 1.2] };

  // ---------------------------------------------------------------- drawing
  function fitCanvas(cv) {
    const r = cv.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    cv.width = Math.max(1, r.width * dpr);
    cv.height = Math.max(1, r.height * dpr);
    const ctx = cv.getContext("2d");
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, r.width, r.height);
    return { ctx, w: r.width, h: r.height };
  }

  // metres -> pixels. The view spans roughly -0.45..0.55 m in x and 0..1.15 m in y.
  function makeView(w, h) {
    const padB = 34, padT = 14;
    const sy = (h - padB - padT) / 1.12;
    const sx = sy;
    const originX = w * 0.42;
    const originY = h - padB;
    return {
      s: sx,
      px: p => ({ x: originX + p.x * sx, y: originY - p.y * sy }),
      inv: q => ({ x: (q.x - originX) / sx, y: (originY - q.y) / sy }),
      originY,
    };
  }

  function arrow(ctx, from, to, color, width, head) {
    const dx = to.x - from.x, dy = to.y - from.y;
    const L = Math.hypot(dx, dy);
    if (L < 0.5) return;
    const ux = dx / L, uy = dy / L;
    const hl = head == null ? Math.min(11, L * 0.35) : head;
    ctx.strokeStyle = color; ctx.fillStyle = color;
    ctx.lineWidth = width || 2.5; ctx.lineCap = "round";
    ctx.beginPath();
    ctx.moveTo(from.x, from.y);
    ctx.lineTo(to.x - ux * hl * 0.85, to.y - uy * hl * 0.85);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(to.x, to.y);
    ctx.lineTo(to.x - ux * hl - uy * hl * 0.42, to.y - uy * hl + ux * hl * 0.42);
    ctx.lineTo(to.x - ux * hl + uy * hl * 0.42, to.y - uy * hl - ux * hl * 0.42);
    ctx.closePath(); ctx.fill();
  }

  // A curved arrow, for moments. sign > 0 draws counter-clockwise.
  function momentArc(ctx, c, r, sign, color, lw) {
    if (Math.abs(sign) < 1e-9) return;
    const dir = sign > 0 ? -1 : 1;           // canvas y is down, so flip
    ctx.strokeStyle = color; ctx.fillStyle = color; ctx.lineWidth = lw || 2.4;
    ctx.beginPath();
    ctx.arc(c.x, c.y, r, dir > 0 ? -2.5 : 0.6, dir > 0 ? 0.6 : -2.5, dir < 0);
    ctx.stroke();
    const a = dir > 0 ? 0.6 : -2.5;
    const tipP = { x: c.x + r * Math.cos(a), y: c.y + r * Math.sin(a) };
    const tang = { x: -Math.sin(a) * dir, y: Math.cos(a) * dir };
    arrow(ctx, { x: tipP.x - tang.x * 8, y: tipP.y - tang.y * 8 }, tipP, color, lw || 2.4, 8);
  }

  function dot(ctx, p, r, fill, stroke) {
    ctx.beginPath(); ctx.arc(p.x, p.y, r, 0, 7);
    ctx.fillStyle = fill; ctx.fill();
    if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 2; ctx.stroke(); }
  }

  function label(ctx, txt, x, y, color, size, align) {
    ctx.font = "600 " + (size || 11) + "px 'Space Grotesk', sans-serif";
    ctx.fillStyle = color; ctx.textAlign = align || "left"; ctx.textBaseline = "middle";
    ctx.fillText(txt, x, y);
    ctx.textAlign = "left";
  }

  const C = {
    bone: "#e8edf7", boneDim: "#5b6884",
    grf: "#5eead4", grav: "#93a1bd", joint: "#7c9bff",
    moment: "#ff6f5e", cop: "#ffd166", arm: "#ff6f5e",
    ink: "#c7d0e0", faint: "#39435c",
  };

  function drawGround(ctx, view, w) {
    ctx.strokeStyle = "#2b3348"; ctx.lineWidth = 2;
    ctx.beginPath(); ctx.moveTo(0, view.originY); ctx.lineTo(w, view.originY); ctx.stroke();
    ctx.strokeStyle = "#222a3c"; ctx.lineWidth = 1;
    for (let x = -8; x < w; x += 11) {
      ctx.beginPath(); ctx.moveTo(x, view.originY); ctx.lineTo(x + 7, view.originY + 7); ctx.stroke();
    }
  }

  function drawLeg(ctx, view, opts) {
    const P = k => view.px(STATE[k]);
    const hip = P("hip"), knee = P("knee"), ankle = P("ankle"), heel = P("heel"), toe = P("toe");
    ctx.lineCap = "round"; ctx.lineJoin = "round";
    const seg = (a, b, wdt, col) => {
      ctx.strokeStyle = col; ctx.lineWidth = wdt;
      ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
    };
    const dim = k => (opts && opts.focus && opts.focus !== k ? C.boneDim : C.bone);
    seg(hip, knee, 9, dim("thigh"));
    seg(knee, ankle, 8, dim("shank"));
    ctx.strokeStyle = dim("foot"); ctx.lineWidth = 7;
    ctx.beginPath(); ctx.moveTo(heel.x, heel.y); ctx.lineTo(toe.x, toe.y); ctx.stroke();
    seg(ankle, { x: (heel.x + toe.x) / 2 * 0.35 + heel.x * 0.65, y: heel.y }, 5, dim("foot"));
    // pelvis stub, so the hip reads as a joint rather than a loose end
    ctx.strokeStyle = C.boneDim; ctx.lineWidth = 7;
    ctx.beginPath(); ctx.moveTo(hip.x, hip.y); ctx.lineTo(hip.x - 26, hip.y - 12); ctx.stroke();
    return { hip, knee, ankle, heel, toe };
  }

  // =========================================================== DEMO 1: free body
  const FBD_TERMS = [
    { id: "grf", eq: "F<sub>ground</sub>", en: "Ground reaction force", pl: "Siła reakcji podłoża",
      d: { en: "Measured by the force plate. Acts through the centre of pressure.",
           pl: "Mierzona przez platformę dynamometryczną. Działa przez środek nacisku." } },
    { id: "grav", eq: "m<sub>foot</sub> g", en: "Segment weight", pl: "Ciężar segmentu",
      d: { en: "Acts at the centre of mass, so it makes no moment about the centre of mass.",
           pl: "Działa w środku masy, więc nie daje momentu względem środka masy." } },
    { id: "fp", eq: "F<sub>ankle</sub>", en: "Joint reaction force", pl: "Siła reakcji w stawie",
      d: { en: "What the shank pushes the foot with across the cut. First unknown.",
           pl: "To, czym podudzie naciska stopę przez przecięcie. Pierwsza niewiadoma." } },
    { id: "mp", eq: "M<sub>ankle</sub>", en: "Net joint moment", pl: "Wypadkowy moment w stawie",
      d: { en: "The turning effect of every muscle, ligament and contact force at the ankle, added together. Second unknown, and the number everybody quotes.",
           pl: "Suma efektów obrotowych wszystkich mięśni, więzadeł i sił kontaktowych w stawie skokowym. Druga niewiadoma i liczba, którą wszyscy podają." } },
  ];

  function buildFbd(host) {
    const wrap = document.createElement("div");
    wrap.className = "id-fbd";
    wrap.innerHTML =
      '<div class="id-fbd-stage"><canvas></canvas></div>' +
      '<div class="id-fbd-side"><div class="id-eqbox">' +
      '<div class="id-eq"><span class="id-eq-l">' + T("Newton", "Newton") + '</span>' +
      '<span class="id-eq-b"><b data-t="fp">F<sub>ankle</sub></b> + <b data-t="grf">F<sub>ground</sub></b> ' +
      '+ <b data-t="grav">m g</b> = m a<sub>com</sub></span></div>' +
      '<div class="id-eq"><span class="id-eq-l">' + T("Euler", "Euler") + '</span>' +
      '<span class="id-eq-b"><b data-t="mp">M<sub>ankle</sub></b> + (r<sub>a</sub> × <b data-t="fp">F<sub>ankle</sub></b>) ' +
      '+ (r<sub>c</sub> × <b data-t="grf">F<sub>ground</sub></b>) = I α</span></div>' +
      '</div><ul class="id-terms"></ul>' +
      '<p class="id-fbd-note">' +
      T("Two equations, two unknowns. That is the whole trick: cutting the segment free turns an impossible measurement into simple algebra.",
        "Dwa równania, dwie niewiadome. Na tym polega cała sztuczka: wycięcie segmentu zamienia niemożliwy pomiar w prostą algebrę.") +
      "</p></div>";
    host.appendChild(wrap);

    const cv = wrap.querySelector("canvas");
    const ul = wrap.querySelector(".id-terms");
    let focus = null;

    FBD_TERMS.forEach(t => {
      const li = document.createElement("li");
      li.className = "id-term"; li.dataset.t = t.id;
      li.innerHTML = '<span class="id-term-eq">' + t.eq + "</span>" +
        '<span class="id-term-b"><b>' + t[PL() ? "pl" : "en"] + "</b>" +
        "<em>" + t.d[PL() ? "pl" : "en"] + "</em></span>";
      li.addEventListener("mouseenter", () => { focus = t.id; paint(); mark(); });
      li.addEventListener("mouseleave", () => { focus = null; paint(); mark(); });
      ul.appendChild(li);
    });
    wrap.querySelectorAll(".id-eq-b b").forEach(b => {
      b.addEventListener("mouseenter", () => { focus = b.dataset.t; paint(); mark(); });
      b.addEventListener("mouseleave", () => { focus = null; paint(); mark(); });
    });
    function mark() {
      wrap.querySelectorAll("[data-t]").forEach(e => e.classList.toggle("on", e.dataset.t === focus));
    }

    function paint() {
      const { ctx, w, h } = fitCanvas(cv);
      // Local view of just the foot, scaled up so the geometry is readable.
      const s = Math.min(w / 0.42, (h - 60) / 0.30);
      const ox = w * 0.30, oy = h - 34;
      const px = p => ({ x: ox + (p.x - STATE.heel.x) * s, y: oy - p.y * s });
      const heel = px(STATE.heel), toe = px(STATE.toe), ankle = px(STATE.ankle);
      const P = segParams();
      const comM = lerp(STATE.heel, STATE.toe, P.foot.com);
      const com = px(comM), cop = px(STATE.cop);
      const mFoot = P.foot.mass * STATE.mass;
      // Scale forces so that one body weight spans about 45% of the panel. Arrow
      // length therefore stays proportional to force: the foot's own weight really
      // is a sliver next to the ground reaction, which is the point.
      const gscale = (h * 0.52) / (STATE.mass * G);

      ctx.strokeStyle = "#2b3348"; ctx.lineWidth = 2;
      ctx.beginPath(); ctx.moveTo(0, oy); ctx.lineTo(w, oy); ctx.stroke();

      const on = k => focus === k;
      const col = (k, c) => (focus && !on(k) ? "#41506e" : c);

      // the foot itself
      ctx.strokeStyle = focus ? "#7b88a6" : C.bone; ctx.lineWidth = 9; ctx.lineCap = "round";
      ctx.beginPath(); ctx.moveTo(heel.x, heel.y); ctx.lineTo(toe.x, toe.y); ctx.stroke();
      ctx.lineWidth = 6;
      ctx.beginPath(); ctx.moveTo(ankle.x, ankle.y); ctx.lineTo(heel.x + (toe.x - heel.x) * 0.16, heel.y); ctx.stroke();

      // ground reaction force
      arrow(ctx, cop, { x: cop.x + STATE.grf.x * gscale, y: cop.y - STATE.grf.y * gscale },
        col("grf", C.grf), on("grf") ? 4.5 : 3);
      dot(ctx, cop, on("grf") ? 6 : 4.5, C.cop);
      label(ctx, T("centre of pressure", "środek nacisku"), cop.x + 8, oy + 16, col("grf", C.cop), 10);

      // weight
      const wl = Math.max(14, mFoot * G * gscale);
      arrow(ctx, com, { x: com.x, y: com.y + wl }, col("grav", C.grav), on("grav") ? 4 : 2.5);
      dot(ctx, com, 5, col("grav", "#0a0e17"), col("grav", C.grav));
      label(ctx, "m g = " + (mFoot * G).toFixed(1) + " N", com.x + 10, com.y + wl + 8, col("grav", C.grav), 10);

      // ankle force + moment (the unknowns)
      const r = solve()[0];
      arrow(ctx, ankle, { x: ankle.x + r.Fp.x * gscale, y: ankle.y - r.Fp.y * gscale },
        col("fp", C.joint), on("fp") ? 4.5 : 3);
      momentArc(ctx, ankle, on("mp") ? 26 : 21, r.Mp, col("mp", C.moment), on("mp") ? 3.4 : 2.4);
      dot(ctx, ankle, 6, "#0a0e17", col("fp", C.joint));
      label(ctx, T("ankle", "staw skokowy"), ankle.x - 10, ankle.y - 34, col("fp", C.ink), 10, "right");

      if (on("mp")) label(ctx, r.Mp.toFixed(1) + " N·m", ankle.x + 30, ankle.y - 26, C.moment, 11);
      if (on("fp")) label(ctx, "(" + r.Fp.x.toFixed(0) + ", " + r.Fp.y.toFixed(0) + ") N",
        ankle.x + 30, ankle.y - 8, C.joint, 11);
    }

    onChange(paint);
    window.addEventListener("resize", paint);
    document.addEventListener("i18n:changed", () => {
      ul.innerHTML = "";
      FBD_TERMS.forEach(t => {
        const li = document.createElement("li");
        li.className = "id-term"; li.dataset.t = t.id;
        li.innerHTML = '<span class="id-term-eq">' + t.eq + "</span>" +
          '<span class="id-term-b"><b>' + t[PL() ? "pl" : "en"] + "</b>" +
          "<em>" + t.d[PL() ? "pl" : "en"] + "</em></span>";
        li.addEventListener("mouseenter", () => { focus = t.id; paint(); mark(); });
        li.addEventListener("mouseleave", () => { focus = null; paint(); mark(); });
        ul.appendChild(li);
      });
      paint();
    });
    paint();
  }

  // ===================================================== DEMO 2: short vs full
  function buildCompare(host) {
    const wrap = document.createElement("div");
    wrap.className = "id-cmp";
    host.appendChild(wrap);

    function paint() {
      const res = solve();
      const rows = res.map((r, i) => {
        const k = r.seg.key;
        // Moments taken about the joint itself, so the unknown joint reaction force
        // drops out on its own. What is left out is the weight and the inertia of
        // every segment between this joint and the ground.
        const short = r.inertial - cross(sub(STATE.cop, r.seg.prox), STATE.grf);
        const full = r.Mp;
        return { k, short, full, r };
      });
      const nm = v => (v >= 0 ? "+" : "") + v.toFixed(1);
      wrap.innerHTML =
        '<div class="id-cmp-eqs">' +
        '<div class="id-cmp-eq id-cmp-short"><span class="id-cmp-tag">' +
        T("short form", "wersja skrócona") + "</span>" +
        "<code>M = I·α − (r × F<sub>ext</sub>)</code></div>" +
        '<div class="id-cmp-eq id-cmp-full"><span class="id-cmp-tag">' +
        T("full form", "wersja pełna") + "</span>" +
        "<code>M<sub>prox</sub> = I·α − M<sub>dist</sub> − (r<sub>prox</sub> × F<sub>prox</sub>) − (r<sub>dist</sub> × F<sub>dist</sub>)</code></div>" +
        "</div>" +
        '<table class="id-tbl"><thead><tr>' +
        "<th>" + T("Joint", "Staw") + "</th>" +
        "<th>" + T("Short form", "Wersja skrócona") + "</th>" +
        "<th>" + T("Full form", "Wersja pełna") + "</th>" +
        "<th>" + T("Error", "Błąd") + "</th></tr></thead><tbody>" +
        rows.map(r => {
          const err = r.short - r.full;
          const rel = Math.abs(r.full) > 1e-6 ? Math.abs(err / r.full) * 100 : 0;
          const cls = rel < 5 ? "ok" : rel < 40 ? "warn" : "bad";
          return "<tr><td>" + JOINT_LABEL[r.k][PL() ? "pl" : "en"] + "</td>" +
            "<td class='num'>" + nm(r.short) + "</td>" +
            "<td class='num'>" + nm(r.full) + "</td>" +
            "<td class='num " + cls + "'>" + nm(err) + " N·m" +
            (rel > 0.5 ? " <small>(" + rel.toFixed(0) + "%)</small>" : "") + "</td></tr>";
        }).join("") +
        "</tbody></table>" +
        '<p class="id-cmp-note">' +
        T("Taking moments about the joint is legitimate, and it is what makes the unknown joint reaction force disappear. What the short form still omits is the weight and the inertia of every segment between that joint and the ground. At the ankle only the foot sits below, so the error is a few percent. Every step up the chain adds another neglected segment. Press Swing, where the foot leaves the ground: with no external force left the short form has nothing to work with, and it is wrong by about 100%, because in swing the segment weights and inertias are the entire answer.",
          "Liczenie momentów względem stawu jest uprawnione i to właśnie sprawia, że nieznana siła reakcji w stawie znika. Wersja skrócona nadal pomija jednak ciężar i bezwładność każdego segmentu między tym stawem a podłożem. W stawie skokowym poniżej jest tylko stopa, więc błąd wynosi kilka procent. Każdy krok w górę łańcucha dokłada kolejny pominięty segment. Naciśnij Wymach, gdy stopa odrywa się od podłoża: bez siły zewnętrznej wersja skrócona nie ma z czym pracować i myli się o około 100%, bo w wymachu ciężary i bezwładności segmentów są całą odpowiedzią.") +
        "</p>";
    }
    onChange(paint);
    document.addEventListener("i18n:changed", paint);
    paint();
  }

  // ======================================================= DEMO 3: the chain
  function buildChain(host) {
    const wrap = document.createElement("div");
    wrap.className = "id-chain";
    wrap.innerHTML =
      '<div class="id-chain-stage"><canvas></canvas>' +
      '<div class="id-hint">' + T("drag the joints, the arrowhead, or the dot on the floor",
        "przeciągaj stawy, grot strzałki albo kropkę na podłodze") + "</div></div>" +
      '<div class="id-chain-side"><div class="id-steps"></div>' +
      '<div class="id-chain-ctrl"></div></div>';
    host.appendChild(wrap);

    const cv = wrap.querySelector("canvas");
    const steps = wrap.querySelector(".id-steps");
    const ctrl = wrap.querySelector(".id-chain-ctrl");
    let view = null, drag = null, hover = null;

    function buildCtrl() {
      ctrl.innerHTML =
        '<label class="id-check"><input type="checkbox" id="idInertia"' +
        (STATE.useInertia ? " checked" : "") + "> <span>" +
        T("include inertia (m·a and I·α)", "uwzględnij bezwładność (m·a oraz I·α)") + "</span></label>" +
        '<div class="id-sliders">' +
        '<div class="id-sl"><label>' + T("Body mass", "Masa ciała") +
        ' <span class="pv" id="idMassV">' + STATE.mass + ' kg</span></label>' +
        '<input type="range" id="idMass" min="40" max="120" step="1" value="' + STATE.mass + '"></div>' +
        '<div class="id-sl"><label>' + T("Height", "Wzrost") +
        ' <span class="pv" id="idHtV">' + STATE.height.toFixed(2) + ' m</span></label>' +
        '<input type="range" id="idHt" min="1.45" max="2.05" step="0.01" value="' + STATE.height + '"></div>' +
        "</div>" +
        '<div class="id-presets">' +
        '<button data-p="heel">' + T("Heel strike", "Kontakt pięty") + "</button>" +
        '<button data-p="mid">' + T("Mid-stance", "Środek podporu") + "</button>" +
        '<button data-p="push">' + T("Push-off", "Odbicie") + "</button>" +
        '<button data-p="swing">' + T("Swing (foot up)", "Wymach (stopa w górze)") + "</button>" +
        "</div>";
      ctrl.querySelector("#idInertia").addEventListener("change", e => {
        STATE.useInertia = e.target.checked; emit();
      });
      const mass = ctrl.querySelector("#idMass"), ht = ctrl.querySelector("#idHt");
      mass.addEventListener("input", () => {
        STATE.mass = +mass.value;
        ctrl.querySelector("#idMassV").textContent = STATE.mass + " kg";
        emit();
      });
      ht.addEventListener("input", () => {
        STATE.height = +ht.value;
        ctrl.querySelector("#idHtV").textContent = STATE.height.toFixed(2) + " m";
        emit();
      });
      ctrl.querySelectorAll(".id-presets button").forEach(b => {
        b.addEventListener("click", () => {
          applyPreset(b.dataset.p);
          // a preset may switch inertia on, so keep the checkbox honest
          const box = ctrl.querySelector("#idInertia");
          if (box) box.checked = STATE.useInertia;
          emit();
        });
      });
    }

    // Postures are drawn to be recognisable rather than taken from any one trial.
    // The mechanics is exact for whatever posture is on screen.
    const PRESETS = {
      heel: {
        hip: { x: -0.035, y: 0.912 }, knee: { x: 0.075, y: 0.500 }, ankle: { x: 0.062, y: 0.072 },
        heel: { x: 0.100, y: 0.012 }, toe: { x: 0.360, y: 0.060 },
        cop: { x: 0.100, y: 0 }, grf: { x: -80, y: 810 },
      },
      mid: {
        hip: { x: 0.020, y: 0.934 }, knee: { x: 0.010, y: 0.505 }, ankle: { x: 0.000, y: 0.075 },
        heel: { x: -0.060, y: 0.025 }, toe: { x: 0.206, y: 0.025 },
        cop: { x: 0.045, y: 0 }, grf: { x: -30, y: 740 },
      },
      push: {
        hip: { x: 0.200, y: 0.928 }, knee: { x: 0.185, y: 0.500 }, ankle: { x: -0.003, y: 0.115 },
        heel: { x: -0.055, y: 0.165 }, toe: { x: 0.175, y: 0.028 },
        cop: { x: 0.120, y: 0 }, grf: { x: 130, y: 800 },
      },
      // Foot off the ground: no external force at all, so the whole answer is
      // segment weight and inertia. This is where the short form collapses.
      swing: {
        hip: { x: 0.000, y: 0.930 }, knee: { x: 0.165, y: 0.535 }, ankle: { x: 0.030, y: 0.130 },
        heel: { x: -0.030, y: 0.105 }, toe: { x: 0.230, y: 0.145 },
        cop: { x: 0.000, y: 0 }, grf: { x: 0, y: 0 },
      },
    };
    function applyPreset(k) {
      const p = PRESETS[k]; if (!p) return;
      if (k === "swing") STATE.useInertia = true;
      ["hip", "knee", "ankle", "heel", "toe", "cop", "grf"].forEach(j => {
        STATE[j] = { x: p[j].x, y: p[j].y };
      });
    }

    const GS = 0.00022;                       // newtons -> metres, for drawing the GRF
    const grfTip = () => ({ x: STATE.cop.x + STATE.grf.x * GS, y: STATE.cop.y + STATE.grf.y * GS });

    function handles() {
      return [
        { k: "hip", p: STATE.hip }, { k: "knee", p: STATE.knee }, { k: "ankle", p: STATE.ankle },
        { k: "heel", p: STATE.heel }, { k: "toe", p: STATE.toe },
        { k: "cop", p: STATE.cop }, { k: "grf", p: grfTip() },
      ];
    }

    function pick(mx, my) {
      if (!view) return null;
      let best = null, bd = 16;
      handles().forEach(h => {
        const q = view.px(h.p);
        const d = Math.hypot(q.x - mx, q.y - my);
        if (d < bd) { bd = d; best = h.k; }
      });
      return best;
    }

    function paint() {
      const f = fitCanvas(cv);
      const ctx = f.ctx;
      view = makeView(f.w, f.h);
      drawGround(ctx, view, f.w);

      const res = solve();
      const px = p => view.px(p);

      // line of action of the ground reaction force, extended, plus moment arms
      const cop = px(STATE.cop), tip = px(grfTip());
      const dx = tip.x - cop.x, dy = tip.y - cop.y, dl = Math.hypot(dx, dy) || 1;
      ctx.save();
      ctx.setLineDash([4, 5]); ctx.strokeStyle = "rgba(94,234,212,.30)"; ctx.lineWidth = 1.4;
      ctx.beginPath();
      ctx.moveTo(cop.x - dx / dl * 900, cop.y - dy / dl * 900);
      ctx.lineTo(cop.x + dx / dl * 900, cop.y + dy / dl * 900);
      ctx.stroke();
      ctx.restore();

      drawLeg(ctx, view, {});

      // perpendicular from each joint to the line of action
      const joints = [["ankle", STATE.ankle], ["knee", STATE.knee], ["hip", STATE.hip]];
      joints.forEach(([name, J]) => {
        const q = px(J);
        const ux = dx / dl, uy = dy / dl;
        const t = (q.x - cop.x) * ux + (q.y - cop.y) * uy;
        const foot = { x: cop.x + ux * t, y: cop.y + uy * t };
        ctx.save();
        ctx.setLineDash([2, 4]); ctx.strokeStyle = "rgba(255,111,94,.55)"; ctx.lineWidth = 1.3;
        ctx.beginPath(); ctx.moveTo(q.x, q.y); ctx.lineTo(foot.x, foot.y); ctx.stroke();
        ctx.restore();
        const dm = Math.hypot(q.x - foot.x, q.y - foot.y) / view.s;
        if (dm > 0.012) {
          label(ctx, (dm * 100).toFixed(1) + " cm",
            (q.x + foot.x) / 2, (q.y + foot.y) / 2 - 8, "rgba(255,111,94,.85)", 9.5);
        }
      });

      // the force itself
      arrow(ctx, cop, tip, C.grf, hover === "grf" || drag === "grf" ? 4.5 : 3.2);
      dot(ctx, tip, hover === "grf" || drag === "grf" ? 7 : 5, C.grf);
      dot(ctx, cop, hover === "cop" || drag === "cop" ? 7 : 5, C.cop);
      label(ctx, Math.hypot(STATE.grf.x, STATE.grf.y).toFixed(0) + " N",
        tip.x + 10, tip.y - 4, C.grf, 11);
      label(ctx, (Math.hypot(STATE.grf.x, STATE.grf.y) / (STATE.mass * G)).toFixed(2) + " BW",
        tip.x + 10, tip.y + 10, "rgba(94,234,212,.7)", 9.5);

      // joints, moments, and per-joint readouts
      res.forEach(r => {
        const J = px(r.seg.prox);
        const strong = Math.min(30, 12 + Math.abs(r.Mp) * 0.10);
        momentArc(ctx, J, strong, r.Mp, C.moment, 2.6);
        dot(ctx, J, hover === r.seg.key ? 7 : 5.5, "#0a0e17", C.joint);
        label(ctx, r.Mp.toFixed(0) + " N·m", J.x + strong + 6, J.y - 6, C.moment, 11.5);
        label(ctx, (r.Mp / STATE.mass).toFixed(2) + " N·m/kg", J.x + strong + 6, J.y + 8,
          "rgba(255,111,94,.65)", 9.5);
      });

      // draggable handles for heel/toe so the foot can be reshaped
      [["heel", STATE.heel], ["toe", STATE.toe]].forEach(([k, p]) => {
        const q = px(p);
        dot(ctx, q, hover === k ? 6 : 4, "#0a0e17", "rgba(232,237,247,.55)");
      });

      renderSteps(res);
    }

    function renderSteps(res) {
      const nm = v => (v >= 0 ? "+" : "") + v.toFixed(1);
      const pl = PL();
      steps.innerHTML = res.map((r, i) => {
        const k = r.seg.key;
        const jl = JOINT_LABEL[k][pl ? "pl" : "en"];
        const sl = SEG_LABEL[k][pl ? "pl" : "en"];
        const perKg = Math.abs(r.Mp / STATE.mass);
        const rng = PLAUSIBLE[k];
        const okCls = perKg <= rng[1] * 1.15 ? "ok" : "bad";
        const okTxt = perKg <= rng[1] * 1.15
          ? T("within the range walking usually produces", "mieści się w zakresie typowym dla chodu")
          : T("larger than walking usually produces", "większy niż zwykle w chodzie");
        return (
          '<div class="id-step">' +
          '<div class="id-step-h"><span class="id-step-n">' + (i + 1) + "</span>" +
          "<b>" + sl + "</b><span class='id-step-j'>&rarr; " + jl + "</span></div>" +
          '<div class="id-step-body">' +
          '<div class="id-row"><span>' + T("known from below", "znane od dołu") + "</span><code>F = (" +
          r.Fdist.x.toFixed(0) + ", " + r.Fdist.y.toFixed(0) + ") N&nbsp;&nbsp;M = " +
          nm(r.Mdist) + " N·m</code></div>" +
          '<div class="id-row"><span>' + T("segment", "segment") + "</span><code>m = " +
          r.seg.m.toFixed(2) + " kg&nbsp;&nbsp;I = " + r.seg.I.toFixed(4) + " kg·m²</code></div>" +
          '<div class="id-row"><span>' + T("joint force", "siła w stawie") + "</span><code>(" +
          r.Fp.x.toFixed(0) + ", " + r.Fp.y.toFixed(0) + ") N</code></div>" +
          '<div class="id-row id-row-sum"><span>' + T("net joint moment", "wypadkowy moment") +
          "</span><code class='id-big'>" + nm(r.Mp) + " N·m</code></div>" +
          '<div class="id-row id-row-chk"><span>' + Math.abs(r.Mp / STATE.mass).toFixed(2) +
          " N·m/kg</span><em class='" + okCls + "'>" + okTxt + "</em></div>" +
          "</div></div>"
        );
      }).join("");
    }

    // ---- pointer handling
    function local(e) {
      const r = cv.getBoundingClientRect();
      return { x: e.clientX - r.left, y: e.clientY - r.top };
    }
    cv.addEventListener("pointermove", e => {
      const m = local(e);
      if (drag) {
        const w = view.inv(m);
        if (drag === "grf") {
          STATE.grf = {
            x: (w.x - STATE.cop.x) / GS,
            y: Math.max(0, (w.y - STATE.cop.y) / GS),
          };
        } else if (drag === "cop") {
          STATE.cop = { x: w.x, y: 0 };
        } else {
          STATE[drag] = { x: w.x, y: Math.max(0, w.y) };
        }
        emit();
      } else {
        const h = pick(m.x, m.y);
        if (h !== hover) { hover = h; cv.style.cursor = h ? "grab" : "default"; paint(); }
      }
    });
    cv.addEventListener("pointerdown", e => {
      const m = local(e);
      drag = pick(m.x, m.y);
      if (drag) { cv.setPointerCapture(e.pointerId); cv.style.cursor = "grabbing"; e.preventDefault(); }
    });
    const up = () => { drag = null; cv.style.cursor = hover ? "grab" : "default"; };
    cv.addEventListener("pointerup", up);
    cv.addEventListener("pointercancel", up);
    cv.addEventListener("pointerleave", () => { hover = null; paint(); });

    buildCtrl();
    onChange(paint);
    window.addEventListener("resize", paint);
    document.addEventListener("i18n:changed", () => {
      buildCtrl();
      wrap.querySelector(".id-hint").textContent =
        T("drag the joints, the arrowhead, or the dot on the floor",
          "przeciągaj stawy, grot strzałki albo kropkę na podłodze");
      paint();
    });
    paint();
  }

  // ======================================================= DEMO 4: BSP tables
  function buildBsp(host) {
    const wrap = document.createElement("div");
    wrap.className = "id-bsp";
    host.appendChild(wrap);

    function paint() {
      const pl = PL();
      const t = TABLES[STATE.table];
      const P = segParams();
      const res = solve();
      const keys = ["foot", "shank", "thigh"];

      // the same posture solved with the other table, for an honest side-by-side
      const otherKey = STATE.table === "winter" ? "deleva" : "winter";
      const save = STATE.table;
      STATE.table = otherKey;
      const other = solve();
      STATE.table = save;

      wrap.innerHTML =
        '<div class="id-bsp-head">' +
        '<div class="id-bsp-tabs">' +
        Object.keys(TABLES).map(k =>
          '<button class="' + (k === STATE.table ? "on" : "") + '" data-tbl="' + k + '">' +
          TABLES[k].name[pl ? "pl" : "en"] + "</button>").join("") +
        "</div>" +
        (t.sexed
          ? '<div class="id-bsp-sex">' +
            ['m', 'f'].map(s =>
              '<button class="' + (s === STATE.sex ? "on" : "") + '" data-sex="' + s + '">' +
              (s === "m" ? T("male", "mężczyźni") : T("female", "kobiety")) + "</button>").join("") +
            "</div>"
          : '<div class="id-bsp-sex id-bsp-nosex">' +
            T("one table for both sexes", "jedna tabela dla obu płci") + "</div>") +
        "</div>" +
        '<p class="id-bsp-note">' + t.note[pl ? "pl" : "en"] +
        ' <span class="id-bsp-cite">' + t.cite + "</span></p>" +
        '<table class="id-tbl"><thead><tr><th>' + T("Segment", "Segment") + "</th>" +
        "<th>" + T("Mass", "Masa") + "</th><th>" + T("CoM", "Środek masy") + "</th>" +
        "<th>" + T("Radius of gyration", "Promień bezwładności") + "</th>" +
        "<th>" + T("This body", "To ciało") + "</th></tr></thead><tbody>" +
        keys.map((k, i) => {
          const s = res[i].seg;
          return "<tr><td>" + SEG_LABEL[k][pl ? "pl" : "en"] + "</td>" +
            "<td class='num'>" + (P[k].mass * 100).toFixed(2) + "%</td>" +
            "<td class='num'>" + (P[k].com * 100).toFixed(1) + "%</td>" +
            "<td class='num'>" + (P[k].rg * 100).toFixed(1) + "%</td>" +
            "<td class='num'>" + s.m.toFixed(2) + " kg · " + s.I.toFixed(4) + " kg·m²</td></tr>";
        }).join("") +
        "</tbody></table>" +
        '<table class="id-tbl id-tbl-cmp"><thead><tr><th>' + T("Joint", "Staw") + "</th>" +
        "<th>" + TABLES[STATE.table].name[pl ? "pl" : "en"] + "</th>" +
        "<th>" + TABLES[otherKey].name[pl ? "pl" : "en"] + "</th>" +
        "<th>" + T("Difference", "Różnica") + "</th></tr></thead><tbody>" +
        keys.map((k, i) => {
          const a = res[i].Mp, b = other[i].Mp, d = a - b;
          const rel = Math.abs(a) > 1e-6 ? Math.abs(d / a) * 100 : 0;
          return "<tr><td>" + JOINT_LABEL[k][pl ? "pl" : "en"] + "</td>" +
            "<td class='num'>" + a.toFixed(1) + "</td>" +
            "<td class='num'>" + b.toFixed(1) + "</td>" +
            "<td class='num " + (rel < 2 ? "ok" : rel < 8 ? "warn" : "bad") + "'>" +
            (d >= 0 ? "+" : "") + d.toFixed(2) + " N·m <small>(" + rel.toFixed(1) + "%)</small></td></tr>";
        }).join("") +
        "</tbody></table>" +
        '<p class="id-bsp-foot">' +
        T("In quiet stance the two tables barely disagree, because the ground force dominates everything else. Turn on inertia in the panel above, or drag the leg into a fast swing posture, and the gap widens: the lighter the external force, the more the answer rests on numbers borrowed from somebody else's body.",
          "W spokojnym podporze obie tabele niemal się nie różnią, bo siła podłoża przeważa nad wszystkim innym. Włącz bezwładność w panelu powyżej albo ustaw nogę w pozycji szybkiego wymachu, a różnica rośnie: im mniejsza siła zewnętrzna, tym bardziej wynik opiera się na liczbach pożyczonych z cudzego ciała.") +
        "</p>";

      wrap.querySelectorAll("[data-tbl]").forEach(b =>
        b.addEventListener("click", () => { STATE.table = b.dataset.tbl; emit(); }));
      wrap.querySelectorAll("[data-sex]").forEach(b =>
        b.addEventListener("click", () => { STATE.sex = b.dataset.sex; emit(); }));
    }
    onChange(paint);
    document.addEventListener("i18n:changed", paint);
    paint();
  }

  // ======================================================== DEMO 5: timeline
  // [ISB] = Challis J, "Biomechanics through time", ISB Now, June 2025.
  const TIMELINE = [
    { y: "1939", src: "context",
      t: { en: "Elftman puts film and a force platform together", pl: "Elftman łączy film z platformą dynamometryczną" },
      d: { en: "Herbert Elftman computes the forces and energy changes in the leg during walking from cine film and a force plate. The method on this page is essentially his, done by hand.",
           pl: "Herbert Elftman oblicza siły i zmiany energii w nodze podczas chodu na podstawie filmu i platformy dynamometrycznej. Metoda z tej strony to w istocie jego metoda, liczona ręcznie." } },
    { y: "1950", src: "context",
      t: { en: "Bresler and Frankel go three-dimensional", pl: "Bresler i Frankel przechodzą do trzech wymiarów" },
      d: { en: "The forces and moments in the leg during level walking are computed in 3-D. This is the paper the modern gait laboratory descends from.",
           pl: "Siły i momenty w nodze podczas chodu po płaskim zostają obliczone w 3-D. To praca, od której wywodzi się współczesna pracownia chodu." } },
    { y: "1955", src: "isb",
      t: { en: "Dempster measures eight cadavers", pl: "Dempster mierzy osiem zwłok" },
      d: { en: "Body segment parameters from eight embalmed cadavers of elderly men. These numbers, tabulated later by Winter, are still the ones most students are taught first.",
           pl: "Parametry segmentów ciała z ośmiu zabalsamowanych zwłok starszych mężczyzn. Te liczby, stabelaryzowane później przez Wintera, nadal jako pierwsze poznaje większość studentów." } },
    { y: "1969", src: "isb",
      t: { en: "Clauser, McConville and Young repeat the exercise", pl: "Clauser, McConville i Young powtarzają badanie" },
      d: { en: "A second cadaver study. The field now has more data, but still from bodies that are old, male and no longer living.",
           pl: "Drugie badanie na zwłokach. Dziedzina ma więcej danych, ale wciąż z ciał starych, męskich i nieżywych." } },
    { y: "1981", src: "isb",
      t: { en: "The ISB Congress meets in Nagoya", pl: "Kongres ISB w Nagoi" },
      d: { en: "One chapter from this congress would go on to be cited more than a thousand times. It was Zatsiorsky and Seluyanov's.",
           pl: "Jeden rozdział z tego kongresu miał zostać zacytowany ponad tysiąc razy. Był to rozdział Zatsiorskiego i Sielujanowa." } },
    { y: "1983", src: "isb", big: true,
      t: { en: "Zatsiorsky and Seluyanov scan the living", pl: "Zatsiorski i Sielujanow prześwietlają żywych" },
      d: { en: "Gamma-mass scanning of 100 living young men, mean age 23.8 years, at the Central Institute of Physical Culture in Moscow. Before this, as the ISB history puts it, reliance had been predominantly on inertial data from cadavers of elderly populations. For the first time the numbers came from bodies like the ones being studied.",
           pl: "Skanowanie gamma 100 żywych młodych mężczyzn o średniej wieku 23,8 roku w Centralnym Instytucie Kultury Fizycznej w Moskwie. Wcześniej, jak ujmuje to historia ISB, polegano głównie na danych bezwładnościowych ze zwłok osób starszych. Po raz pierwszy liczby pochodziły z ciał podobnych do badanych." } },
    { y: "1985", src: "isb",
      t: { en: "Regression equations follow", pl: "Pojawiają się równania regresji" },
      d: { en: "The work is extended so segment parameters can be predicted from ordinary body measurements, which is what makes the table usable on a real person in a clinic.",
           pl: "Praca zostaje rozszerzona tak, by parametry segmentów dało się przewidzieć ze zwykłych pomiarów ciała, co dopiero czyni tabelę użyteczną wobec realnego pacjenta." } },
    { y: "1990", src: "isb",
      t: { en: "Fifteen women are added", pl: "Dodano piętnaście kobiet" },
      d: { en: "With Chugunova, the data set finally includes female subjects. Fifteen of them, against one hundred men. Every sex-specific parameter in use today rests on that sample.",
           pl: "Wraz z Czugunową zbiór danych obejmuje wreszcie kobiety. Piętnaście, wobec stu mężczyzn. Każdy używany dziś parametr zależny od płci opiera się na tej próbie." } },
    { y: "1996", src: "isb",
      t: { en: "de Leva makes the data usable", pl: "de Leva czyni dane użytecznymi" },
      d: { en: "The Soviet measurements were referenced to bony landmarks, but motion capture works in joint centres. de Leva converts the whole table, and in doing so turns a landmark study into the default setting of most modelling software.",
           pl: "Radzieckie pomiary odnoszono do punktów kostnych, a rejestracja ruchu operuje środkami stawów. De Leva przelicza całą tabelę i tym samym zmienia przełomowe badanie w domyślne ustawienie większości oprogramowania modelującego." } },
    { y: "2002", src: "isb",
      t: { en: "Zatsiorsky describes what it cost", pl: "Zatsiorski opisuje, ile to kosztowało" },
      d: { en: "Writing years later, he recounts the Soviet approval process for publishing abroad: signatures from a seven-person university committee, and if the manuscript was revised, the whole process had to be repeated. The table in your software has a bureaucratic history as well as a scientific one.",
           pl: "Pisząc po latach, opisuje radziecką procedurę zgody na publikację za granicą: podpisy siedmioosobowej komisji uczelnianej, a jeśli maszynopis poprawiono, całą procedurę trzeba było powtórzyć. Tabela w Twoim oprogramowaniu ma nie tylko historię naukową, ale i biurokratyczną." } },
    { y: "2007", src: "delp", big: true,
      t: { en: "OpenSim is given away", pl: "OpenSim zostaje udostępniony" },
      d: { en: "Delp and colleagues release a full musculoskeletal modelling and simulation platform as open source, so that a result computed in one laboratory can be checked in another. Everything on this page is a two-dimensional shadow of what that software does in three.",
           pl: "Delp ze współpracownikami udostępnia pełną platformę do modelowania i symulacji mięśniowo-szkieletowej jako otwarte oprogramowanie, aby wynik obliczony w jednej pracowni dał się sprawdzić w innej. Wszystko na tej stronie to dwuwymiarowy cień tego, co to oprogramowanie robi w trzech." } },
  ];

  function buildTimeline(host) {
    const wrap = document.createElement("div");
    wrap.className = "id-time";
    host.appendChild(wrap);
    let open = 5;                              // start on Zatsiorsky & Seluyanov

    function paint() {
      const pl = PL();
      wrap.innerHTML =
        '<div class="id-time-rail">' +
        TIMELINE.map((e, i) =>
          '<button class="id-time-node' + (i === open ? " on" : "") + (e.big ? " big" : "") +
          '" data-i="' + i + '"><span>' + e.y + "</span></button>").join("") +
        "</div>" +
        '<div class="id-time-card">' +
        "<h4>" + TIMELINE[open].t[pl ? "pl" : "en"] + "</h4>" +
        "<p>" + TIMELINE[open].d[pl ? "pl" : "en"] + "</p>" +
        '<span class="id-time-src">' +
        (TIMELINE[open].src === "isb"
          ? T("from the ISB history, Challis 2025", "za historią ISB, Challis 2025")
          : TIMELINE[open].src === "delp"
            ? "Delp et al. 2007"
            : T("standard history of the field", "standardowa historia dziedziny")) +
        "</span></div>";
      wrap.querySelectorAll(".id-time-node").forEach(b =>
        b.addEventListener("click", () => { open = +b.dataset.i; paint(); }));
    }
    document.addEventListener("i18n:changed", paint);
    paint();
  }

  // ============================================================ tools section
  const TOOLS = [
    {
      name: "OpenSim", tag: { en: "free · open source · Stanford", pl: "bezpłatny · otwarty · Stanford" },
      url: "https://simtk.org/projects/opensim",
      d: {
        en: "The standard platform for musculoskeletal modelling. Builds a model, solves inverse kinematics and inverse dynamics, then estimates the muscle forces that would produce the motion. Runs on Windows, macOS and Linux.",
        pl: "Standardowa platforma do modelowania mięśniowo-szkieletowego. Buduje model, rozwiązuje kinematykę i dynamikę odwrotną, a następnie szacuje siły mięśniowe, które wytworzyłyby dany ruch. Działa na Windows, macOS i Linux.",
      },
      steps: {
        en: ["Scale the generic model to the subject's dimensions and mass",
             "Inverse kinematics: find the joint angles that best fit the markers",
             "Residual reduction: adjust the model so the motion and the measured forces agree",
             "Computed muscle control: find muscle excitations that reproduce the motion"],
        pl: ["Skalowanie modelu ogólnego do wymiarów i masy badanego",
             "Kinematyka odwrotna: znalezienie kątów stawowych najlepiej pasujących do markerów",
             "Redukcja resztek: dopasowanie modelu tak, by ruch i zmierzone siły się zgadzały",
             "Computed muscle control: znalezienie pobudzeń mięśni odtwarzających ruch"],
      },
    },
    {
      name: "OpenSim Creator", tag: { en: "free · model building", pl: "bezpłatny · budowa modeli" },
      url: "https://opensimcreator.com/",
      d: { en: "A modern editor for building OpenSim models directly, with immediate visual feedback. Much gentler than editing the XML by hand, which is how it used to be done.",
           pl: "Nowoczesny edytor do budowania modeli OpenSim wprost, z natychmiastowym podglądem. Znacznie przyjaźniejszy niż ręczna edycja XML, jak robiło się dawniej." },
    },
    {
      name: "OpenCap", tag: { en: "free · two phones", pl: "bezpłatny · dwa telefony" },
      url: "https://www.opencap.ai/",
      d: { en: "Markerless capture from two phone videos, feeding an OpenSim model. It is what the Knee Control page on this site uses, and it removes the force plate and camera array from the entry price.",
           pl: "Rejestracja bezmarkerowa z dwóch filmów telefonicznych, zasilająca model OpenSim. Korzysta z niej strona Kontrola kolana na tym serwisie i znosi konieczność posiadania platformy i zestawu kamer." },
    },
    {
      name: "ezc3d / BTK", tag: { en: "free · file access", pl: "bezpłatny · dostęp do plików" },
      url: "https://github.com/pyomeca/ezc3d",
      d: { en: "Gait laboratories store everything in C3D files. These libraries open them from Python, MATLAB or Octave, which is the first practical step in doing any of this with real data.",
           pl: "Pracownie chodu przechowują wszystko w plikach C3D. Te biblioteki otwierają je z Pythona, MATLAB-a lub Octave, co jest pierwszym praktycznym krokiem do pracy na prawdziwych danych." },
    },
  ];

  function buildTools(host) {
    function paint() {
      const pl = PL();
      host.innerHTML = TOOLS.map(t =>
        '<div class="id-tool">' +
        '<div class="id-tool-h"><h3>' + t.name + "</h3>" +
        '<span class="id-tool-tag">' + t.tag[pl ? "pl" : "en"] + "</span></div>" +
        "<p>" + t.d[pl ? "pl" : "en"] + "</p>" +
        (t.steps
          ? '<ol class="id-tool-steps">' + t.steps[pl ? "pl" : "en"].map(s => "<li>" + s + "</li>").join("") + "</ol>"
          : "") +
        '<a href="' + t.url + '" target="_blank" rel="noopener">' +
        T("open", "otwórz") + " &rarr;</a></div>").join("");
    }
    document.addEventListener("i18n:changed", paint);
    paint();
  }

  // ------------------------------------------------------------------- boot
  function boot() {
    buildFbd(document.getElementById("idFbd"));
    buildCompare(document.getElementById("idCompare"));
    buildChain(document.getElementById("idChain"));
    buildBsp(document.getElementById("idBsp"));
    buildTimeline(document.getElementById("idTime"));
    buildTools(document.getElementById("idTools"));
    wireQuotes(document);
    document.addEventListener("i18n:changed", () => { hideTip(); wireQuotes(document); });
    emit();
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
